---
# tasks file for slacko



  - name: Clone a repo with separate git directory
    ansible.builtin.git:
      repo: https://github.com/LeonardoDG2084/iaac_slacko-api
      dest: /opt/slacko-api/
    tags:
      - gitclone


  - name: Instalar NTP
    apt:
       name: ntp
       state: present
    notify:
       - ntp
       - crond
       - env
    tags:
       - ntp   
     

  - name: copiar configuração do ntp
    copy:
        src: ntp.conf
        dest: /etc/ntp.conf
    notify: 
      - horacerta
    tags: 
      - horacerta
     

  - name: Instalaçao do MongoDB
    apt: 
      name: mongodb
      state: present
      update_cache: yes
    tags:
        - mongodb
    notify:
        - restart mongodb


  - name: Instalaço dos requerimentos do Python
    pip:
      requirements: /opt/slacko-api/requeriments.txt
    tags: 
      - python


  - name: Criar o diretório pela variável do path
    file:
        path: "{{ path }}"
        state: directory
        owner: root
        group: root 
        mode: 0755 

  - name: Copiar o script .sh
    copy:
        src: slacko-api.sh
        dest: "{{ path }}"
        owner: root
        group: root
        mode: 0755
    tags: 
      - script



  - name: Copiar arquivo que transforma script em service
    copy:
      src: slacko-api.service
      dest: /etc/systemd/system
      owner: root
      group: root
    notify:
      - copy.service
      - start.service
    tags: 
      - copy.service




