---
 - hosts: remoto
   gather_facts: True
   become: yes
   roles: 
    - slacko

   vars:
      ntppath: /etc/
      path: /opt/slacko-api/
      env:
         envlin: export TZ=America/Sao_Paulo
   
    
